### ISSUE TITLE
V2 Router02. swapExactTokensForTokens produces 'UniswapV2: INSUFFICIENT_INPUT_AMOUNT' for cyclic path

### ISSUE THREAD

**Issue by NakedKoala** [Uniswap/v2-periphery#127]
I am having trouble with specifying cyclic path for the `swapExactTokensForTokens` function. The use-case of having the same input and output token is cyclic arbitrage.

I tried submit actual transaction on rinkeby testnet and simulate using ether.js's callstatic on mainnet. The result is the same.

Attempt1 :
path = [WETHAddress, UNIAddress] => success
https://rinkeby.etherscan.io/tx/0xc170bbc7e5ac846872d93146afcb1ccedf999e2aa7a2a954ed45b4e15679a0f5

Attempt2:
path = [UNIAddress, WETHAddress] => sucesss
https://rinkeby.etherscan.io/tx/0x4f7c2af1ba8874ac640dd55fa715149db5caa1ee9d90d51520c450eee959fae6

Attempt3:
path = [WETHAddress, UNIAddress, WETHAddress] =>  'UniswapV2: INSUFFICIENT_INPUT_AMOUNT'
https://rinkeby.etherscan.io/tx/0xf7f945c537c31c9fe6b6e27ba82c8fa6440d80324737f0d2440d92b57669c57f

Can you explain why cyclic path doesn't work ?  Is this not supported at all ( in that case, I will have no choice but deploy my own proxy contract to make 2 calls to the router )

**Comment by EpicsDAOClient** [comment]
Hey Buidleeeeeeeeeeeeeeers🙌
This issue is related to Epics Quest🚨
You get 1,000 $EPCT if you solve this💰

Please join this Quest from here👇
https://alpha.epics.dev/quest/UXVlc3Q6MTA=

WAGBI🔨
Have a good day☀

**Comment by venom-d** [comment]
hello, did you solve the problem?

**Comment by sirgarfieldc** [comment]
Yes

**Comment by venom-d** [comment]
> Yes

how did you deal with it, I also encountered a related problem

**Comment by sirgarfieldc** [comment]
> > Yes
> 
> how did you deal with it, I also encountered a related problem

Going in and out of the same pool within the same transaction is not supported by V2 pool. (read the swap function and you will see why).

**Comment by venom-d** [comment]
> > > Yes
> > 
> > 
> > how did you deal with it, I also encountered a related problem
> 
> Going in and out of the same pool within the same transaction is not supported by V2 pool. (read the swap function and you will see why).

ok thanks
