### ISSUE TITLE
unitest swapExactETHForTokens

### ISSUE THREAD

**Issue by Sexy-J** [Uniswap/v2-periphery#128]
![image](https://user-images.githubusercontent.com/28497767/178692687-2960459e-124a-4bc6-9739-a98d4ccf5d05.png)
why my gas is 108770

**Comment by hensha256** [comment]
When you change the implementation of a function, it changes the gas it uses. When you then run the tests they fail because they have changed the gas - to flag it as a change.
If you want the test to pass and update the gas snapshots you can set the environment variable `UPDATE_SNAPSHOT=1`.
