### ISSUE TITLE
BUG: getAmountsOut not works on BaseChain for V2 Router

### ISSUE THREAD

**Issue by TangMonk** [Uniswap/v2-periphery#178]
Is **0xD6e0Bc285be97C75861910f4d2cFD4AC61DD629d** for V2 Router?

When I call `getAmountsOut` it return error:

```
Error: Returned error: execution reverted
```

<img width="909" alt="image" src="https://github.com/Uniswap/v2-periphery/assets/3498786/456155ab-1c73-4acf-aed0-ec90083f597b">

But I can call `getPair` on [V2 Factory](0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6):

<img width="580" alt="image" src="https://github.com/Uniswap/v2-periphery/assets/3498786/7e48e4dc-5811-4b03-9efc-7dddd9ed910e">

**Comment by hensha256** [comment]
You're using the wrong router :) the correct one is:
0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6

**Comment by TangMonk** [comment]
> You're using the wrong router :) the correct one is: 0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6

I meant the V2 router, But you gave V2 Factory 😂

**Comment by hensha256** [comment]
oops sorry! let me look closer

**Comment by TangMonk** [comment]
> oops sorry! let me look closer

Thank you, Waiting for you reply 😄😄😄

**Comment by hensha256** [comment]
https://basescan.org/address/0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24

**Comment by TangMonk** [comment]
> https://basescan.org/address/0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24*

Thank you very much! 😄😄😄

**Comment by TangMonk** [comment]
@hensha256 But seems [Quoter](https://github.com/Uniswap/uniswap-v3-periphery/blob/v1.0.0/contracts/lens/Quoter.sol) is not avalible on Base in [Uniswap Deployments Doc](https://docs.uniswap.org/contracts/v3/reference/deployments)
